name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (z.B. 1.2.3)'
        required: true


jobs:
  update-and-tag:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Update pom.xml version
        working-directory: ./backend
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.version }}

      - name: Update package.json version
        working-directory: ./frontend
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Install npm dependencies
        working-directory: ./frontend
        run: npm install

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          git config --global user.signingkey "$GPG_KEY_ID"
          git config --global commit.gpgsign true
          git config --global user.name "David Bohl"
          git config --global user.email "david@davidbohl.org"
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Commit version changes
        run: |
          git add ./backend/pom.xml ./frontend/package.json ./frontend/package-lock.json
          git commit -S -m "Bump version to ${{ github.event.inputs.version }}"

      - name: Push changes to main branch
        run: git push origin HEAD:main

      - name: Create and push tag
        run: |
          git tag -s v${{ github.event.inputs.version }} -m "Release v${{ github.event.inputs.version }}"
          git push origin v${{ github.event.inputs.version }}
      - name: Merge main into dev
        run: |
          git checkout dev
          git pull origin dev
          git merge main
          git push origin dev
      - name: Trigger Docker build via repository_dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PUSH_PAT }}
          event-type: tag-created
          client-payload: '{"tag": "v${{ github.event.inputs.version }}"}'
